package com.juziwl.commonlibrary.dao;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.util.Log;

import org.greenrobot.greendao.AbstractDaoMaster;
import org.greenrobot.greendao.database.StandardDatabase;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseOpenHelper;
import org.greenrobot.greendao.identityscope.IdentityScopeType;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/**
 * Master of DAO (schema version 1): knows all DAOs.
 */
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 1;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(Database db, boolean ifNotExists) {
        AreaDao.createTable(db, ifNotExists);
        ArticleDao.createTable(db, ifNotExists);
        CircleTopicClassDao.createTable(db, ifNotExists);
        ClassDynamicDao.createTable(db, ifNotExists);
        ClassDynInfoDao.createTable(db, ifNotExists);
        ClazzDao.createTable(db, ifNotExists);
        ClazzStartEndTimeDao.createTable(db, ifNotExists);
        CourseFileDao.createTable(db, ifNotExists);
        HisMsgDao.createTable(db, ifNotExists);
        MsgDao.createTable(db, ifNotExists);
        NewTimeDao.createTable(db, ifNotExists);
        OnlineSchoolDao.createTable(db, ifNotExists);
        ProvinceCityDistinctDao.createTable(db, ifNotExists);
        SearchHistoryDao.createTable(db, ifNotExists);
        ServiceItemDao.createTable(db, ifNotExists);
        UserDao.createTable(db, ifNotExists);
        WeiDuMsgDao.createTable(db, ifNotExists);
    }

    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(Database db, boolean ifExists) {
        AreaDao.dropTable(db, ifExists);
        ArticleDao.dropTable(db, ifExists);
        CircleTopicClassDao.dropTable(db, ifExists);
        ClassDynamicDao.dropTable(db, ifExists);
        ClassDynInfoDao.dropTable(db, ifExists);
        ClazzDao.dropTable(db, ifExists);
        ClazzStartEndTimeDao.dropTable(db, ifExists);
        CourseFileDao.dropTable(db, ifExists);
        HisMsgDao.dropTable(db, ifExists);
        MsgDao.dropTable(db, ifExists);
        NewTimeDao.dropTable(db, ifExists);
        OnlineSchoolDao.dropTable(db, ifExists);
        ProvinceCityDistinctDao.dropTable(db, ifExists);
        SearchHistoryDao.dropTable(db, ifExists);
        ServiceItemDao.dropTable(db, ifExists);
        UserDao.dropTable(db, ifExists);
        WeiDuMsgDao.dropTable(db, ifExists);
    }

    /**
     * WARNING: Drops all table on Upgrade! Use only during development.
     * Convenience method using a {@link DevOpenHelper}.
     */
    public static DaoSession newDevSession(Context context, String name) {
        Database db = new DevOpenHelper(context, name).getWritableDb();
        DaoMaster daoMaster = new DaoMaster(db);
        return daoMaster.newSession();
    }

    public DaoMaster(SQLiteDatabase db) {
        this(new StandardDatabase(db));
    }

    public DaoMaster(Database db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(AreaDao.class);
        registerDaoClass(ArticleDao.class);
        registerDaoClass(CircleTopicClassDao.class);
        registerDaoClass(ClassDynamicDao.class);
        registerDaoClass(ClassDynInfoDao.class);
        registerDaoClass(ClazzDao.class);
        registerDaoClass(ClazzStartEndTimeDao.class);
        registerDaoClass(CourseFileDao.class);
        registerDaoClass(HisMsgDao.class);
        registerDaoClass(MsgDao.class);
        registerDaoClass(NewTimeDao.class);
        registerDaoClass(OnlineSchoolDao.class);
        registerDaoClass(ProvinceCityDistinctDao.class);
        registerDaoClass(SearchHistoryDao.class);
        registerDaoClass(ServiceItemDao.class);
        registerDaoClass(UserDao.class);
        registerDaoClass(WeiDuMsgDao.class);
    }

    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }

    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }

    /**
     * Calls {@link #createAllTables(Database, boolean)} in {@link #onCreate(Database)} -
     */
    public static abstract class OpenHelper extends DatabaseOpenHelper {
        public OpenHelper(Context context, String name) {
            super(context, name, SCHEMA_VERSION);
        }

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(Database db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }

    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name) {
            super(context, name);
        }

        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(Database db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

}
